version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-npm-dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: node modules installation
          command: npm install
      - save_cache:
          paths:
            - ~/workspace/node_modules
          key: v1-npm-dependency-cathe-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm test -- --coverage

  build:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-npm-dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  build_check:
    jobs:
      - test
      - build:
          requires:
            - test