version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.0

    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependency-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - ~/workspace/node_modules
          key: v1-dependency-{{ checksum "package.json" }}
      - run:
          name: test
          command: yarn test

  build:
    docker:
      - image: circleci/node:8.11.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-npm-dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build

workflows:
  version: 2
  build_check:
    jobs:
      - test
      - build:
          requires:
            - test